config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :trades
  resources :tickers
  root to: 'trades#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ticker.rb
class Ticker < ApplicationRecord
  belongs_to :user
end

app/models/trade.rb
class Trade < ApplicationRecord
  belongs_to :user
  belongs_to :ticker
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/tickers_controller.rb
class TickersController < ApplicationController
  before_action :set_ticker, only: [:show, :edit, :update, :destroy]

  # GET /tickers
  # GET /tickers.json
  def index
    @tickers = Ticker.all
  end

  # GET /tickers/1
  # GET /tickers/1.json
  def show
  end

  # GET /tickers/new
  def new
    @ticker = Ticker.new
  end

  # GET /tickers/1/edit
  def edit
  end

  # POST /tickers
  # POST /tickers.json
  def create
    @ticker = Ticker.new(ticker_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @ticker.save
        format.html { redirect_to @ticker, notice: 'Ticker was successfully created.' }
        format.json { render :show, status: :created, location: @ticker }
      else
        format.html { render :new }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickers/1
  # PATCH/PUT /tickers/1.json
  def update
    respond_to do |format|
      if @ticker.update(ticker_params)
        format.html { redirect_to @ticker, notice: 'Ticker was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticker }
      else
        format.html { render :edit }
        format.json { render json: @ticker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickers/1
  # DELETE /tickers/1.json
  def destroy
    @ticker.destroy
    respond_to do |format|
      format.html { redirect_to tickers_url, notice: 'Ticker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticker
      @ticker = Ticker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticker_params
      params.require(:ticker).permit(:name, :enabled)
    end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  before_action :set_trade, only: [:show, :edit, :update, :destroy]

  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
  end

  # GET /trades/new
  def new
    @trade = Trade.new
  end

  # GET /trades/1/edit
  def edit
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(trade_params.merge(user_id: current_user.id))

    puts 'HALP ' * 30
    puts trade_params.inspect

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render :show, status: :created, location: @trade }
      else
        format.html { render :new }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trades/1
  # PATCH/PUT /trades/1.json
  def update
    respond_to do |format|
      if @trade.update(trade_params)
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { render :show, status: :ok, location: @trade }
      else
        format.html { render :edit }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade.destroy
    respond_to do |format|
      format.html { redirect_to trades_url, notice: 'Trade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trade
      @trade = Trade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trade_params
      params.require(:trade).permit(:amount, :ticker_id, :shares)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tickers_helper.rb
module TickersHelper
end

app/helpers/trades_helper.rb
module TradesHelper
  def array_for_options
    Ticker.all.select(:id, :name).map { |t| [t.name, t.id] }
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InvestmentTracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Trades', trades_path %>
    <%= link_to 'Tickers', tickers_path %>
    <%= yield %>
  </body>
</html>

app/views/tickers/_form.html.erb
<%= form_with(model: ticker, local: true) do |form| %>
  <% if ticker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ticker.errors.count, "error") %> prohibited this ticker from being saved:</h2>

      <ul>
      <% ticker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ticker_name %>
  </div>

  <div class="field">
    <%= form.label :enabled %>
    <%= form.check_box :enabled, id: :ticker_enabled %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tickers/edit.html.erb
<h1>Editing Ticker</h1>

<%= render 'form', ticker: @ticker %>

<%= link_to 'Show', @ticker %> |
<%= link_to 'Back', tickers_path %>

app/views/tickers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tickers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Enabled</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickers.each do |ticker| %>
      <tr>
        <td><%= ticker.name %></td>
        <td><%= ticker.enabled %></td>
        <td><%= ticker.user.email %></td>
        <td><%= link_to 'Show', ticker %></td>
        <td><%= link_to 'Edit', edit_ticker_path(ticker) %></td>
        <td><%= link_to 'Destroy', ticker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticker', new_ticker_path %>

app/views/tickers/new.html.erb
<h1>New Ticker</h1>

<%= render 'form', ticker: @ticker %>

<%= link_to 'Back', tickers_path %>

app/views/tickers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ticker.name %>
</p>

<p>
  <strong>Enabled:</strong>
  <%= @ticker.enabled %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticker.user %>
</p>

<%= link_to 'Edit', edit_ticker_path(@ticker) %> |
<%= link_to 'Back', tickers_path %>

app/views/trades/_form.html.erb
<%= form_with(model: trade, local: true) do |form| %>
  <% if trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% trade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :shares %>
    <%= form.text_field :shares, id: :trade_shares %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount, id: :trade_amount %>
  </div>

  <div class="field">
    <%= form.label :ticker_id %>
    <%= form.select(:ticker_id, options_for_select(array_for_options)) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trades</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>Shares</th>
      <th>Amount</th>
      <th>Cost</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trades.each do |trade| %>
      <tr>
        <td><%= trade.ticker.name %></td>
        <td><%= trade.shares %></td>
        <td><%= trade.amount %></td>
        <td><%= trade.shares * trade.amount %></td>
        <td><%= trade.user.email %></td>
        <td><%= link_to 'Show', trade %></td>
        <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
        <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<h1>New Trade</h1>

<%= render 'form', trade: @trade %>

<%= link_to 'Back', trades_path %>

app/views/trades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticker:</strong>
  <%= @trade.ticker.name %>
</p>

<p>
  <strong>Shares:</strong>
  <%= @trade.shares %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @trade.amount %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @trade.shares * @trade.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @trade.user.email %>
</p>

<%= link_to 'Edit', edit_trade_path(@trade) %> |
<%= link_to 'Back', trades_path %>